### ISSUE TITLE
No feature request on child repository.

### ISSUE THREAD

**Issue by gmponos** [guzzle/.github#1]
When I am on Guzzle I don't see the feature request.

![image](https://user-images.githubusercontent.com/5675248/71376194-66b4ca80-25c9-11ea-83f8-11af91438f6b.png)

**Comment by sagikazarmark** [comment]
Looks like common templates are only used when no templates are defined in the repo :\

**Comment by gmponos** [comment]
I hope this will be the only problem and not appear only if .github folder is not present...

**Comment by sagikazarmark** [comment]
Fixed in guzzle/guzzle#2504
