### ISSUE TITLE
Openstatck api : error Call to undefined method GuzzleHttp\Utils::chooseHandler() in Transport/HandlerStack.php

### ISSUE THREAD

**Issue by guyzoum77** [guzzle/.github#2]
**PHP version**: x.y.z (hint: `php --version`)
i use php 7.4

**Description**

Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /opt/lampp/htdocs/projets/whmcs_v792/whmcs/modules/addons/c4a_vps/vendor/php-opencloud/openstack/src/Common/Transport/HandlerStack.php:14
Stack trace:
#0 /opt/lampp/htdocs/projets/whmcs_v792/whmcs/modules/addons/c4a_vps/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(135): OpenStack\Common\Transport\HandlerStack::create()
#1 /opt/lampp/htdocs/projets/whmcs_v792/whmcs/modules/addons/c4a_vps/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(94): OpenStack\Common\Service\Builder->getStack(Object(Closure))
#2 /opt/lampp/htdocs/projets/whmcs_v792/whmcs/modules/addons/c4a_vps/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(82): OpenStack\Common\Service\Builder->stockHttpClient(Array, 'Identity\\v3')
#3 /opt/lampp/htdocs/projets/whmcs_v792/whmcs/modules/addons/c4a_vps/vendor/php-opencloud/openstack/src/OpenStack.php(150): OpenStack\Common\Service\Builder->createService('Identity\\v3', Array)
#4 /opt/lampp/htdocs/projets/whmcs_v792/whmcs/modules/addons/c4a_vps/lib/Client/Controller.php(72): OpenStack\OpenStack->identityV3()

**How to reproduce**

**Possible Solution**

**Additional context**

**Comment by sagikazarmark** [comment]
Please open issues in the guzzle repo.
